scope = {
    "Home": "https://breachforums.st/",
    "Databases": "https://breachforums.st/Announcement-Database-Index",
    "Forum - Announcements": "https://breachforums.st/Forum-Announcements",
    "Forum - Suggestions & Bug Reports": "https://breachforums.st/Forum-Suggestions-Bug-Reports",
    "Forum - Introductions": "https://breachforums.st/Forum-Introductions",
    "Forum - World News": "https://breachforums.st/Forum-World-News",
    "Forum - Technology News": "https://breachforums.st/Forum-Technology-News",
    "Forum - The Lounge": "https://breachforums.st/Forum-The-Lounge",
    "Forum - Random Discussion": "https://breachforums.st/Forum-Random-Discussion",
    "Forum - Achievements": "https://breachforums.st/Forum-Achievements",
    "Forum - Serious Discussion": "https://breachforums.st/Forum-Serious-Discussion",
    "Forum - Anime & Manga": "https://breachforums.st/Forum-Anime-Manga",
    "Forum - Giveaways & Freebies": "https://breachforums.st/Forum-Giveaways-Freebies",
    "Forum - Music & Videos": "https://breachforums.st/Forum-Music-Videos",
    "Forum - General Tutorials": "https://breachforums.st/Forum-General-Tutorials",
    "Forum - Leaks": "https://breachforums.st/Forum-Leaks",
    "Forum - Games": "https://breachforums.st/Forum-Games",
    "Forum - Databases": "https://breachforums.st/Forum-Databases",
    "Forum - Stealer Logs": "https://breachforums.st/Forum-Stealer-Logs",
    "Forum - Other Leaks": "https://breachforums.st/Forum-Other-Leaks",
    "Forum - Scam Reports": "https://breachforums.st/Forum-Scam-Reports",
    "Forum - Services": "https://breachforums.st/Forum-Services",
    "Forum - Sellers Place": "https://breachforums.st/Forum-Sellers-Place",
    "Forum - Buyers Place": "https://breachforums.st/Forum-Buyers-Place",
    "Statistics": "https://breachforums.st/stats.php",
}
