# Start with a Debian base image
FROM debian:bullseye

# Set environment variables to minimize interactive prompts
ENV DEBIAN_FRONTEND=noninteractive

# Update the package list and install dependencies
RUN apt-get update && apt-get install -y --no-install-recommends \
    tor \
    wget \
    curl \
    gnupg \
    python3.10 \
    python3-pip \
    apt-transport-https \
    ca-certificates \
    fonts-liberation \
    libappindicator3-1 \
    libasound2 \
    libgbm1 \
    libnspr4 \
    libnss3 \
    libx11-xcb1 \
    libxcomposite1 \
    libxcursor1 \
    libxdamage1 \
    libxrandr2 \
    xvfb libnss3 libatk-bridge2.0-0 libgbm1 \
    xdg-utils && \
    apt-get clean && rm -rf /var/lib/apt/lists/*

# Add the Google Chrome repository and install Chrome
RUN wget -q -O - https://dl.google.com/linux/linux_signing_key.pub | gpg --dearmor > /usr/share/keyrings/google-chrome.gpg && \
    echo "deb [arch=amd64 signed-by=/usr/share/keyrings/google-chrome.gpg] http://dl.google.com/linux/chrome/deb/ stable main" > /etc/apt/sources.list.d/google-chrome.list && \
    apt-get update && apt-get install -y --no-install-recommends google-chrome-stable && \
    apt-get clean && rm -rf /var/lib/apt/lists/*

RUN echo "SETTING UP SCREEN --------------"

# Install Python packages
RUN pip3 install --no-cache-dir \
    requests \
    selenium \
    webdriver_manager 

# Optional: Add a basic Tor configuration file
RUN mkdir -p /etc/tor
WORKDIR /app/test
COPY . .

# Expose ports if using Tor
RUN pip install stem
EXPOSE 9050 9051
RUN pip install elasticsearch

# Set the entrypoint (default to bash for flexibility)
CMD ["/bin/bash", "-c", "./run.sh"]

